// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginHistoryReq struct {
	PageBaseInfo
	StartTime string `form:"start_time,optional"` // 开始时间，格式：2006-01-02 15:04:05
	EndTime   string `form:"end_time,optional"`   // 结束时间
	IP        string `form:"ip,optional"`         // IP地址筛选
}

type LoginHistoryResp struct {
	Entries    []LoginHistoryItem `json:"entries"`
	TotalCount int64              `json:"total_count"`
}

type LoginReq struct {
	Mobile   string `json:"mobile" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"`
	Password string `json:"password" validate:"required,min=8,max=32"`
	Code     string `json:"code" validate:"required,len=6,regexp=^\\d{6}$"`
}

type RegisterResp struct {
	UserId string `json:"user_id"` // UUID v7
}

type ResetPasswordConfirmReq struct {
	Mobile   string `json:"mobile" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"`
	Code     string `json:"code" validate:"required,len=6,regexp=^\\d{6}$"`
	Password string `json:"password" validate:"required,min=8,max=32"`
}

type ResetPasswordConfirmResp struct {
	Message string `json:"message"`
}

type ResetPasswordRequestReq struct {
	Mobile string `json:"mobile" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"`
}

type ResetPasswordRequestResp struct {
	Message string `json:"message"`
}

type SendRegisterCodeReq struct {
	Mobile string `json:"mobile" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"`
}

type SendRegisterCodeResp struct {
	Message string `json:"message"`
}

type SendResetCodeReq struct {
	Mobile string `json:"mobile" validate:"required,len=11,regexp=^1[3-9]\\d{9}$"`
}

type SendResetCodeResp struct {
	Message string `json:"message"`
}
