// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "github.com/jinguoxing/idrm-cursor-demo/api/internal/handler/auth"
	"github.com/jinguoxing/idrm-cursor-demo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/login-history",
					Handler: auth.LoginHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/reset-password/confirm",
					Handler: auth.ResetPasswordConfirmHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/reset-password/request",
					Handler: auth.ResetPasswordRequestHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/send-register-code",
					Handler: auth.SendRegisterCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/send-reset-code",
					Handler: auth.SendResetCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/auth"),
	)
}
